### ISSUE TITLE
python setup instructions

### ISSUE THREAD

**Issue by jordandc20** [learn-co-curriculum/phase-0-wsl2-env-verification-py#2]
### Canvas Link

https://learning.flatironschool.com/courses/6611/pages/verify-and-troubleshoot-your-wsl2-environment-setup?module_item_id=525435

### Concern

Hi! when going through the setup there is no guidance on installing Python, but during the "verify and troubleshoot" step there are instructions to check your Python installation. Looks like these checks are in here by mistake or instructions for installing Python are missing?

**Comment by lizbur10** [comment]
Thanks for bringing this to our attention @jordandc20 ! The Python installation instructions were moved to Phase 3, but we missed this! It should now be fixed.

Thanks for contributing to the Flatiron School curriculum 💙
